//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vovk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcname
    {
        public int Classid { get; set; }
        public string Func_name { get; set; }
    }
}
